import 'package:flutter/material.dart';
class ConstString{
 static const app_name="ReserVision Messenger";
 static const welcome_to="Welcome To";
 static const reservision_tex="Reservision";
 static const your_dream="Your dream is just click away";
 static const email_tex="Email";
 static const email_hinttex="Enter Email";
 static const password_tex= "Password";
 static const password_hinttex= "Enter Password";
 static const remember_me="Remember Me";
 static const forgot_password="Forgot Password ?";
 static const login_tex="Login";
 static const google_tex="Google";
 static const messages_tex="Messages";
 static const customAleart_title="Alert";
 static const emailEmpty_description="Please enter emailaddress";
 static const validEmail_description="Please enter valid emailaddress";
 static const passwordEmpty_description="Please enter  password";
 static const validPassword_description="Please enter minimum 8 characters, at least 1 uppercase letter, 1 lowercase letter, 1 number and 1 special character";
 static const templates_tex="Templates";
 static const contacts_tex="Contacts";
 static const more_tex="More";
 static const ejConcierge_Ride="EJ CONCIERGE RIDE";
 static const cencle_tex="CANCEL";
 static const add_Contact="Add Contact";
 static const done_tex="DONE";
 static const add_tex="add";
 static const photo_tex="Photo";
 static const firstname_tex="First name";
 static const lastname_tex="Last name";
static const editScreenContacts_tex="CONTACTS";
static const edit_tex="EDIT";
}